# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# Network Settings
#
hostname: vccw.dev
ip: 192.168.33.10

#
# WordPress Settings
#
version: latest
lang: en_US
title: Welcome to the VCCW
multisite: false
rewrite_structure: /archives/%post_id%

#
# WordPress Path
#
wp_siteurl: ''  # Path to the WP_SITEURL like "wp"
wp_home: ''     # Path to the WP_HOME like "wp"

#
# WordPress User
#
admin_user: admin
admin_pass: admin
admin_email: vccw@example.com

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins:
  - debug-bar

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: ''

#
# WordPress Options
#
options:
  blogdescription: Hello VCCW.

#
# WordPress Multisite Options
#
multisite_options: {}

#
# The values of wp-config.php
#
force_ssl_admin: false
wp_debug: true
savequeries: false

#
# Addtional PHP code in the wp-config.php
#
extra_wp_config: |
  // Addtional PHP code in the wp-config.php
  // These lines are inserted by VCCW.
  // You can place addtional PHP code here!

#
# Theme unit testing
#
theme_unit_test: false
theme_unit_test_uri: https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml
# theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml

#
# RubyGems
#
ruby_gems:
  - bundler
  - wordmove

#
# NPM modules
#
npms: []

#
# composer
#
composers:
  - hirak/prestissimo:*
  - phpunit/phpunit:*
  - squizlabs/php_codesniffer:*
  - wp-coding-standards/wpcs:*
  # - phpmd/phpmd:*
  # - sebastian/phpcpd:*
  # - phploc/phploc:*
  # - phing/phing:*

#
# wp-cli package commands
#
wp_cli_packages:
  - vccw/wp-cli-scaffold-movefile:@stable
